import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overscroll-y-none overflow-y-auto bg-purple-50`}
      >
        {children}
        <footer className="bg-purple-900 text-white mt-12 border-t-2 border-yellow-500">
          <div className="max-w-6xl mx-auto px-4 py-8">
            <div className="grid md:grid-cols-3 gap-8">
              <div>
                <h4 className="font-semibold mb-3 text-yellow-400">Data Sources</h4>
                <ul className="text-sm text-purple-200 space-y-1">
                  <li>USGS Water Data</li>
                  <li>NOAA National Weather Service</li>
                  <li>Climate Impacts Group, UW</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-3 text-yellow-400">Contact</h4>
                <p className="text-sm text-purple-200">
                  Climate Impacts Group<br />
                  University of Washington<br />
                  cig@uw.edu
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-3 text-yellow-400">Acknowledgements</h4>
                <p className="text-sm text-purple-200">
                  Funded by NOAA and the State of Washington. 
                  Built in collaboration with local communities.
                </p>
                <div className="mt-2 text-xs text-yellow-300 border-t border-yellow-600 pt-2">
                  Open Data License: CC BY 4.0
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
